### ISSUE TITLE
Support mono on windows

### ISSUE THREAD

**Issue by rokups** [rbfx/rbfx#112]
It should be possible to use mono on windows with both msvc or mingw compilers.

**Comment by rokups** [comment]
It seems that msbuild that comes with mono does not support new project format. Mono developers advise using msbuild from microsoft. Finding it is troublesome however. So in case you are reading this and want mono+mingw support - pull requests are welcome :trollface:

**Comment by carlcc** [comment]
Have you considered to embed mono in to Editor and Player?

**Comment by rokups** [comment]
Well yes and no. Beauty of rbfx is that so far it runs on whatever platform .net runtime is available (with one exception). .net core is a bit of special case as it is rather new so build system is not really adapted to it. But otherwise it runs with either .net framework or mono. I would like to keep it that way.

With that said - we will need to embed mono for mobile platforms anyway. When that happens we will be just one step away (mainly build system tweaking) from doing same on desktop. So in the long run - yes, we could have mono embedded into player, this would be enabled by a build system parameter.

**Comment by bvanevery** [comment]
Today by RTFM I determined that CMAKE_VS_MSBUILD_COMMAND is the correct way to find where msbuild is, if a Visual Studio generator is being used.  That means it must be guarded with if(MSVC).  Going through UrhoCommon.cmake, I am noting a number of Mono-isms as I try to get the C# build to work without any kind of Mono.  For instance, my next step is dealing with "sn".  The logic for the case uses hasn't been thought through.  I have really no familiarity with .NET or MONO.  Is it actually reasonable for both to be in use at the same time?

**Comment by rokups** [comment]
Mono is still used on linux so that is where those mono-isms come from. Attempt to set `MONO_PATH` on windows would indeed conflict and break, hence no mono support on windows. Reason for lack of support is very simple: debugging mono programs in visual studio is not possible without jumping through hoops. Since absolute majority expect to use VS on windows i did not really rush to implement support for runtime that will likely remain unused for the most part. With advent of .net core 3.0 and upcoming .net 5 i dont even know if there is a point in supporting mono at all. We will see.

**Comment by rokups** [comment]
Closing as `wontfix`, because now we target official microsoft .net framework on all platforms.
