### ISSUE TITLE
Comparison ops for some classes are incorrect

### ISSUE THREAD

**Issue by eugeneko** [rbfx/rbfx#197]
Keeping this as issue so we don't forget about it...

This shall be either fixed or reverted
https://github.com/rokups/rbfx/commit/66d27e76682fe84037f10f261aa158045052a0a1

**Comment by rokups** [comment]
IIRC this was added to make C# bindings compile. These types are used in some containers that are wrapped by C#. Those containers failed to compile without these operators.
