### ISSUE TITLE
Geometry import is broken

### ISSUE THREAD

**Issue by nem0** [rbfx/rbfx#235]
Steps to reproduce:
1. put some fbx in your data
2. start the editor
3. asset importer might or might not run
4. regardless of 3, mdl is not created

Expected result: I should be able to import fbx files without manually invoking external exe from command line

**Comment by dumganhar** [comment]
I got this issue too. Any solutions?

**Comment by rokups** [comment]
Nope. In the long run we should drop AssetImporter completely and replace it with custom gltf/fbx importer. This will not happen any time soon.

**Comment by nem0** [comment]
This is not an issue with assimp. It does not import any files, even files which assimp has no problem with.

**Comment by eugeneko** [comment]
@nem0 AssetImporter != assimp

**Comment by nem0** [comment]
My bad. So completely drop AssetImporter (and assimp) and use just fbx2gltf + some gltf lib?
