### ISSUE TITLE
NavigationMesh: Missing FindPath

### ISSUE THREAD

**Issue by Mac767** [rbfx/rbfx#288]
Hi,

it seems that the FindPath functions are missing in the c# classes.

**Comment by rokups** [comment]
They are [ignored](https://github.com/rokups/rbfx/blob/master/Source/Urho3D/CSharp/Swig/Urho3D.i#L707) for some reason i do not remember. You could try uncommenting this line. Chances are it might work.

**Comment by gleblebedev** [comment]
I can try to port sample to c# to see what is missing.

**Comment by Mac767** [comment]
That would be great.
My goal was to use the CrowdNavigation but there happens nothing after SetCrowdTarget. I subscripted to all Crowd events but no one will be fired.
Afterthis I tried to switch to NavigationMesh to check if there are some problems with building the navigation mesh. But here is the missing functions my problem.

At the moment I used  gleblebedev nugets but I'm trying to build the master source now and uncomment the line.

**Comment by gleblebedev** [comment]
0.3.7.292 should have FindPath now. I didn't test it, just uncommented the line.

**Comment by Mac767** [comment]
Thanks for the nuget.
FindPath returns some way points. CrowdNavigation seems to work, too. My navigation mesh was not successfully builded.

**Comment by gleblebedev** [comment]
Case closed then?

**Comment by Mac767** [comment]
If the FindPath is kept in NavigationMesh then yes

**Comment by gleblebedev** [comment]
Just in case - the .net version of navigation sample
https://github.com/gleblebedev/Urho3DNet.Samples/blob/main/src/Urho3DNet.Samples/NavigationDemo.cs
