### ISSUE TITLE
Building with CMake

### ISSUE THREAD

**Issue by Patillac** [rbfx/rbfx#329]
I'm trying to follow the CMake build instructions but I can't figure it out. If I clone the repo to C:\thirdparty\rbfx then where do the CMakeLists.txt and main.cpp files go? The contents of the provided CMakeLists.txt suggest it should be in the parent folder of Urho3D, but that's the Source folder which already contains a CMakeLists.txt. When I create a MyAwesomeGame folder within the Source folder, then CMake complains that it can't find the subdirectory Urho3D.

**Comment by tijon1** [comment]
Rbfx folder goes into the folder with cmakelists.txt and main.cpp

**Comment by Patillac** [comment]
Thanks. I had to rename the rbfx folder to Urho3D to get the header include paths to generate properly, but it's all working now.

**Comment by tijon1** [comment]
You can just rename the urho3d to rbfx in cmakelists.txt but doesn't matter, if that solution got it working, then good.
