### ISSUE TITLE
Shaders not working

### ISSUE THREAD

**Issue by Patillac** [rbfx/rbfx#333]
I'm trying to add some existing PostProcess effects to the samples just to see if I can get them working, but I haven't figured out what's wrong yet. In Urho3D after adding the postprocess xml to the renderpath and setting the shader parameters it would then draw on the screen. In rbfx I can load the postprocess xml and the commands are added to the render path, and I can get the existing shader parameters and see that they're correct and are changing from false to true, but enabling the commands doesn't change what's drawn on the screen. I've also tested modifying the XML files to point to incorrect shaders names, and it never produces any errors as if to suggest it never tried to load them in the first place.

For example, in DiffOutline.xml I have:

```
    <pass name="shadow" vs="Shadow" ps="Shadow" />
    <pass name="outline" vs="Outline" ps="Outline" psdefines="MASK" depthwrite="false" />
```

The debug log shows that the Shadow shader is loaded, but not the Outline shader. If I change vs="Shadow" to vs="ShaXdow" then I get errors saying it can't find ShaXdow, but if I change vs="Outline" to vs="OutXline" then it doesn't produce any errors.

Any ideas why they stopped working?

**Comment by rokups** [comment]
XML renderpaths are no longer supported with new renderer. Either build with `-DURHO3D_LEGACY_RENDERER=1` do it "The New Way" that @eugeneko will explain.
