### ISSUE TITLE
Editor: Icons scale with node

### ISSUE THREAD

**Issue by niansa** [rbfx/rbfx#334]
Icons scale with node but new icon scale gets applied when reloading scene only.

**Comment by gleblebedev** [comment]
It only reproducable when scene is loaded from file. Can't repro it by changing values in the editor.

![image](https://user-images.githubusercontent.com/2943937/142782363-d60b2ec5-ec68-4482-98a3-64d98b01d9c4.png)

**Comment by niansa** [comment]
Closing, because new editor doesn't have icons.
