### ISSUE TITLE
Editor: Crash when creating new folder

### ISSUE THREAD

**Issue by niansa** [rbfx/rbfx#335]
Well, here's the log:

    [12:15:39] [debug] [main] : Created directory /tmp/Resources/New Folder
    Editor: /home/nils/Programme/OSS/rbfx/Source/ThirdParty/imgui/imgui.cpp:8155: void ImGuiStackSizes::CompareWithCurrentState(): Assertion `SizeOfIDStack == window->IDStack.Size && "PushID/PopID or TreeNode/TreePop Mismatch!"' failed.
    './Editor' terminated by signal SIGABRT (Abort)

I am on opensuse tumbleweed btw

**Comment by gleblebedev** [comment]
Urho3D.dll!ImGuiStackSizes::CompareWithCurrentState() Line 8155	C++
>	Urho3D.dll!ImGui::End() Line 7021	C++
 	Urho3D.dll!ImGui::EndChild() Line 5415	C++
 	libEditor.dll!Urho3D::ResourceTab::RenderWindowContent() Line 375	C++
 	libEditor.dll!Urho3D::Tab::RenderWindow() Line 146	C++
 	libEditor.dll!Urho3D::Editor::OnUpdate(eastl::hash_map<Urho3D::StringHash,Urho3D::Variant,eastl::hash<Urho3D::StringHash,void>,eastl::equal_to<Urho3D::StringHash>,eastl::allocator,0> & args) Line 376	C++
 	libEditor.dll!Urho3D::Editor::Start::__l2::<lambda>(Urho3D::StringHash __formal, eastl::hash_map<Urho3D::StringHash,Urho3D::Variant,eastl::hash<Urho3D::StringHash,void>,eastl::equal_to<Urho3D::StringHash>,eastl::allocator,0> & args) Line 256	C++
 	[External Code]	
 	Urho3D.dll!Urho3D::EventHandler11Impl::Invoke(eastl::hash_map<Urho3D::StringHash,Urho3D::Variant,eastl::hash<Urho3D::StringHash,void>,eastl::equal_to<Urho3D::StringHash>,eastl::allocator,0> & eventData) Line 389	C++
 	Urho3D.dll!Urho3D::Object::OnEvent(Urho3D::Object * sender, Urho3D::StringHash eventType, eastl::hash_map<Urho3D::StringHash,Urho3D::Variant,eastl::hash<Urho3D::StringHash,void>,eastl::equal_to<Urho3D::StringHash>,eastl::allocator,0> & eventData) Line 130	C++
 	Urho3D.dll!Urho3D::Object::SendEvent(Urho3D::StringHash eventType, eastl::hash_map<Urho3D::StringHash,Urho3D::Variant,eastl::hash<Urho3D::StringHash,void>,eastl::equal_to<Urho3D::StringHash>,eastl::allocator,0> & eventData) Line 390	C++
 	Urho3D.dll!Urho3D::Engine::Update() Line 742	C++
 	Urho3D.dll!Urho3D::Engine::RunFrame() Line 554	C++
 	Urho3D.dll!Urho3D::Application::Run() Line 149	C++
