### ISSUE TITLE
Crash on plugin unload when I exit C# editor.

### ISSUE THREAD

**Issue by eugeneko** [rbfx/rbfx#349]
STR
1. Open `bin/` in Editor
2. Close Editor

![image](https://user-images.githubusercontent.com/8576192/146666971-74d3f299-2b85-45c0-985d-6ed4fd288dd4.png)
![image](https://user-images.githubusercontent.com/8576192/146666986-ccc4c120-87f6-452d-bbe1-720762c67f13.png)

**Comment by rokups** [comment]
I can not reproduce. Anything different in your `bin/` project?
