### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by KatekovAnton** [rbfx/rbfx#354]
https://user-images.githubusercontent.com/992894/146766012-770c9a13-0bb5-4633-a68b-72374c067885.mp4

Rendering artifacts:
- shadow bleeding in some camera positions
- ground darkening in a distance

Env:
- OpenGL
- MacOS

**Comment by rokups** [comment]
Need a way to reproduce the issue in order to fix it.

**Comment by KatekovAnton** [comment]
I shared my repo with @eugeneko he will take a look later
