### ISSUE TITLE
KinematicCharacterController affects rigid bodies near it

### ISSUE THREAD

**Issue by eugeneko** [rbfx/rbfx#356]
Which is probably not desired behavior since it's not really stable.

It can be fixed by setting `btCollisionObject::CF_NO_CONTACT_RESPONSE` in `KinematicCharacterController` to disable interaction with bodies _and_ removing all `m_ghostObject->hasContactResponse()` checks in `btKinematicCharacterController`.

I am not 100% sure what's the proper solution is here.

**Comment by gleblebedev** [comment]
Maybe is should be an option of the controller?

**Comment by eugeneko** [comment]
@gleblebedev I don't understand why Bullet has this check in first place.
Like... Is there _any_ scenario where you _don't_ want your ghost object to have collisions with the world?
This is the point of controller -- to interact with the world.

**Comment by eugeneko** [comment]
Or maybe it should be solved via collision masks and layers instead.
To mark character as character, and make all other objects ignore character layer... I dunno.
