### ISSUE TITLE
Editor Suggestion: Add the ability to reference an existing node as a "prefab"

### ISSUE THREAD

**Issue by TrevorCash** [rbfx/rbfx#36]
Adding the ability to load in a seperately saved node file in "Prefab" mode.  whereas multiple prefabs from the same file can be loaded - and a change to one will issue the same respective change to the other prefabs.  Nodes that are in "Prefab" mode could be marked somehow in the hierarchy  so that it is obvious to the user that a change to one will effect the others.

This may not really be possible with the current architecture I don't know.  The editor would have to be smart about it.

**Comment by TrevorCash** [comment]
Could code from (https://discourse.urho3d.io/t/poor-mans-prefab-system/4681/2)  be added to support this feature?

**Comment by eugeneko** [comment]
Prefabs are now fully supported in the Editor and the engine.
