### ISSUE TITLE
Android build failed with URHO3D_GLES3 

### ISSUE THREAD

**Issue by talarcon** [rbfx/rbfx#362]
Hi, I've tried to build the engine with flag to support OpenGLES 3.0, but it's not working.
This is the error
![image](https://user-images.githubusercontent.com/10941288/151048911-2f2cd979-687c-4f7e-b291-bdf539685327.png)

It's not supported yet?

**Comment by gleblebedev** [comment]
Nor officially. It works in my branch

**Comment by gleblebedev** [comment]
https://github.com/gleblebedev/rbfx/tree/custom_rbfx

**Comment by talarcon** [comment]
Thanks @gleblebedev!

**Comment by gleblebedev** [comment]
@rokups shall I make a PR?

**Comment by rokups** [comment]
why not 👍🏻

**Comment by gleblebedev** [comment]
@rokups here is the PR
https://github.com/rbfx/rbfx/pull/368

**Comment by eugeneko** [comment]
We fully migrated to GLES3, so it should not be relevant
