### ISSUE TITLE
Rendering issues #2

### ISSUE THREAD

**Issue by KatekovAnton** [rbfx/rbfx#363]
Unfortunately I can still see shadow rendering issues just like in  #354 ... OpenGL/MacOS

https://user-images.githubusercontent.com/992894/151142250-2b5b7f3e-16d1-4e21-b72e-0aa84f67a961.mp4

**Comment by eugeneko** [comment]
Well fuck.
Can you make an isolated scene download? It cannot be using that much different resources.

**Comment by eugeneko** [comment]
Also, does this issue go away if you disable "Focus To Scene" in the Light?

**Comment by KatekovAnton** [comment]
@eugeneko 

> Also, does this issue go away if you disable "Focus To Scene" in the Light?

Yes bug disappears!

**Comment by KatekovAnton** [comment]
Yep it is fixed, my bad! Thank you
