### ISSUE TITLE
Terrain Baked Lightmap glitch

### ISSUE THREAD

**Issue by Mac767** [rbfx/rbfx#377]
Hi

please find attached a sample to reproduce the terrain baked lightmap glitch.
It need these 4 parts:
- terrain with baked lightmap
- one or more baked or mixed light
- one directional light in mixed or realtime mode attached to camera node
- one or more model with emissive texture

The emissive texture will be sometimes blend over the terrain instead of the lightmap.
[BakedLightmap.zip](https://github.com/rbfx/rbfx/files/8074217/BakedLightmap.zip)

**Comment by eugeneko** [comment]
I don't see actual baking of the lightmap. Do you do that in your application?

**Comment by Mac767** [comment]
Do you mean LightBaker.Bake?
It seems this Subsystem/Component is currently not available in c#.

**Comment by eugeneko** [comment]
@gleblebedev since it's related to the nuget, I'll ping u.
Do you build Urho3D.Glow in your nuggets?
Can you expose basic lightmapping API there? Should be easy.
