### ISSUE TITLE
Building tutorial please？

### ISSUE THREAD

**Issue by SoNewBee** [rbfx/rbfx#389]
I am a noob and I want to use c# with rbfx.
I am trying to build this engine from source code,but there are problems.
I am using vs2017 and I have installed .net framework 4.7.1-4.7.2.
But cmake point out it can not find dot net execute file.I don't know what it is.I searched my computer but there was nothing called "dotnet.exe".
So I installed .net 6.0,then I can add "dotnet.exe" filepath to cmake,then I can generate project with cmake.But vs2017 can not recognize .net 6.0.
Then I installed vs2022.
But it can not build eastl.lib.
I like this project and I really want to try it.So any advice please？

**Comment by rokups** [comment]
You are almost there. What's the issue with eastl? It builds fine for me with new VS. Did you delete cmake cache dir after switching visual studio version?

**Comment by gleblebedev** [comment]
@SoNewBee is there a reason why nuget package doesn't work for you?

**Comment by SoNewBee** [comment]
Thanks for your reply.
Here are errors.
![image](https://user-images.githubusercontent.com/51787223/157854526-7b2abe77-ec9c-4c19-a092-ea7a9840cb10.png)
![image](https://user-images.githubusercontent.com/51787223/157854579-f60469d5-41ac-4542-8111-157d165c5590.png)

**Comment by SoNewBee** [comment]
> You are almost there. What's the issue with eastl? It builds fine for me with new VS. Did you delete cmake cache dir after switching visual studio version?

Everytime I want to rebuild project,I will delete all file from my computer.

**Comment by SoNewBee** [comment]
> @SoNewBee is there a reason why nuget package doesn't work for you?

Sorry, I don't know.Maybe you can have a look with my screenshot?

**Comment by gleblebedev** [comment]
> Sorry, I don't know.Maybe you can have a look at my screenshot?
I've never had the issue you have and I it looks very strange to me.

If you prefer to use c# to make a game on top of rbfx you can just use the https://www.nuget.org/packages/unofficial.Urho3DNet/
It supports .net4 along with .net core, UWP and mobile platforms.

You can install this solution template and generate the project from it: https://marketplace.visualstudio.com/items?itemName=GlebLebedev.Urho3DNet

**Comment by Kinogar** [comment]
I think the version of visual studio might matter. Seems to have something to do with the compiler option /Zc:static_assert- where adding it resolves the error.

In EASTL/scripts/CMake/CommonCppFlags.cmake I have:
```
elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest /W4 /permissive-")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.31.30911.95")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:static_assert-")
    endif()
endif()
```

**Comment by SoNewBee** [comment]
> > Sorry, I don't know.Maybe you can have a look at my screenshot?
> > I've never had the issue you have and I it looks very strange to me.
> 
> If you prefer to use c# to make a game on top of rbfx you can just use the https://www.nuget.org/packages/unofficial.Urho3DNet/ It supports .net4 along with .net core, UWP and mobile platforms.
> 
> You can install this solution template and generate the project from it: https://marketplace.visualstudio.com/items?itemName=GlebLebedev.Urho3DNet

Awesome work,But...Does this vsix file compatible with vs2022?
I can not install it and I received an error.
"VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products."

**Comment by SoNewBee** [comment]
> I think the version of visual studio might matter. Seems to have something to do with the compiler option /Zc:static_assert- where adding it resolves the error.
> 
> In EASTL/scripts/CMake/CommonCppFlags.cmake I have:
> 
> ```
> elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest /W4 /permissive-")
>     if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.31.30911.95")
>         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:static_assert-")
>     endif()
> endif()
> ```

OK,thx...
I might try it later.

**Comment by SoNewBee** [comment]
> I think the version of visual studio might matter. Seems to have something to do with the compiler option /Zc:static_assert- where adding it resolves the error.
> 
> In EASTL/scripts/CMake/CommonCppFlags.cmake I have:
> 
> ```
> elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest /W4 /permissive-")
>     if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.31.30911.95")
>         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:static_assert-")
>     endif()
> e

**Comment by SoNewBee** [comment]
> I think the version of visual studio might matter. Seems to have something to do with the compiler option /Zc:static_assert- where adding it resolves the error.
> 
> In EASTL/scripts/CMake/CommonCppFlags.cmake I have:
> 
> ```
> elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
>     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++latest /W4 /permissive-")
>     if(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL "19.31.30911.95")
>         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:static_assert-")
>     endif()
> endif()
> ```

OK...It works,thank you!
But...How to build C# Project?
I don't know exactly what wiki mean,especially step 1 and 2.
Any help please?

**Comment by SoNewBee** [comment]
I have tried this method.
1.make a C# empty project by vs2022.
2.copy 2 folders and 3 dlls like this(the path is in this picture too).
![1](https://user-images.githubusercontent.com/51787223/158068045-dca2b221-dafa-4de5-8cd9-c3b2974cba7f.png)
3.open vs2022 and add program.cs which is in 102_CSharpProject,run.
Then I got an error:"System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The specified module could not be found."
![2](https://user-images.githubusercontent.com/51787223/158068409-7a0764e5-298e-4d33-ac1f-0110a5decc00.png)
The error shows in line 123.
But when I deleted line 118,this program can be started.
Why...?
Any better advice please?

**Comment by rokups** [comment]
Those instructions are bit outdated. Easiest way is using one of few existing nuget packages:
https://www.nuget.org/packages/rbfx.Urho3DNet/ - official
https://www.nuget.org/packages/unofficial.Urho3DNet/ - unofficial, also supports mobiles

**Comment by SoNewBee** [comment]
> Collaborator

OK...I have tried nuget packages,But I prefer to build it from source and I think I am almost there.I don't want to give up.
Could you please tell me the meaning of line 101 and line 123?
Why it can run after delete them?
I wonder if there would be more strange "rule"?
BTW,I build rbfx and sample by using "Release x64" option.

**Comment by rokups** [comment]
Constructing a C# project from source would not be completely straightforward, but i can give you few pointers.

1. Create a CMake project and include rbfx via `add_subdirectory()` (Sample script [here](https://github.com/rbfx/rbfx/wiki/first-application), skip `add_executable()`.
2. Create a C# project (.csproj) with your code
3. Include your .csproj in CMake project:
```cmake
add_target_csharp(
    TARGET YourProjectName
    EXE
    PROJECT path/to/your.csproj
    OUTPUT ${CMAKE_BINARY_DIR}/${DEST_BIN_DIR_CONFIG}/YourProjectName${CMAKE_EXECUTABLE_SUFFIX}
    DEPENDS Urho3DNet)
```

I think this should be mostly enough for you to have a project that builds engine and your C# project. No manual file copying will be needed. You should be able to open visual studio solution generated by CMake and access both engine and your C# source code and work from there.

**Comment by SoNewBee** [comment]
> Constructing a C# project from source would not be completely straightforward, but i can give you few pointers.
> 
> 1. Create a CMake project and include rbfx via `add_subdirectory()` (Sample script [here](https://github.com/rbfx/rbfx/wiki/first-application), skip `add_executable()`.
> 2. Create a C# project (.csproj) with your code
> 3. Include your .csproj in CMake project:
> 
> ```cmake
> add_target_csharp(
>     TARGET YourProjectName
>     EXE
>     PROJECT path/to/your.csproj
>     OUTPUT ${CMAKE_BINARY_DIR}/${DEST_BIN_DIR_CONFIG}/YourProjectName${CMAKE_EXECUTABLE_SUFFIX}
>     DEPENDS Urho3DNet)
> ```
> 
> I think this should be mostly enough for you to have a project that builds engine and your C# project. No manual file copying will be needed. You should be able to open visual studio solution generated by CMake and access both engine and your C# source code and work from there.

......
I really don't know how to do this,even the first step.
Could you please tell me whether my method is wrong?
Can I just fix it on the basis of my method?

**Comment by eugeneko** [comment]
> I really don't know how to do this,even the first step.
> Could you please tell me whether my method is wrong?
> Can I just fix it on the basis of my method?

You see, there are standard ways of doing things.
Standard routine for CMake project (like rbfx) is to use CMake to generate IDE-specific project.

People sometimes try different ways, but they are not actively maintained and may get broken as time goes.

Other option is to somehow use nuget by @gleblebedev, which doesn't let you modify C++ side, but offers easy integration on C# side.

So, these are 3 options. If you tell me you goals, how you want to use rbfx, I can help you pick the best way for you.

**Comment by rokups** [comment]
> I really don't know how to do this,even the first step.

You do need at very least a basic C++ and CMake knowledge to work with rbfx source code. We do not have resources to teach people C++. I suggest you use one of linked nuget packages or learn strings and ropes of C++ before revisiting building from source code.

**Comment by SoNewBee** [comment]
> > I really don't know how to do this,even the first step.
> > Could you please tell me whether my method is wrong?
> > Can I just fix it on the basis of my method?
> 
> You see, there are standard ways of doing things. Standard routine for CMake project (like rbfx) is to use CMake to generate IDE-specific project.
> 
> People sometimes try different ways, but they are not actively maintained and may get broken as time goes.
> 
> Other option is to somehow use nuget by @gleblebedev, which doesn't let you modify C++ side, but offers easy integration on C# side.
> 
> So, these are 3 options. If you tell me you goals, how you want to use rbfx, I can help you pick the best way for you.

wow,that's very kind of you.
I wonder if there is a way that can make things simple.For instance,copy folders and dlls to a C# project,then add reference to dlls and we can get a rbfx C# project.Just like I did.
Maybe my thought is ridiculous but...I am a student and feel headache with c++/cmake things.That is too professional for noobs like me.And that's why I choose rbfx not urho3d.
No offence,will you add functions like godot?I have learnt something about 2D games.In godot,we can do anything easily.Including writing codes and using editor.
Maybe I should use nuget as @rokups said?
Or...maybe I should use engines like unity/UE?I wonder if It is too early for me to get in touch with open source project.

**Comment by SoNewBee** [comment]
> > I really don't know how to do this,even the first step.
> > Could you please tell me whether my method is wrong?
> > Can I just fix it on the basis of my method?
> 
> You see, there are standard ways of doing things. Standard routine for CMake project (like rbfx) is to use CMake to generate IDE-specific project.
> 
> People sometimes try different ways, but they are not actively maintained and may get broken as time goes.
> 
> Other option is to somehow use nuget by @gleblebedev, which doesn't let you modify C++ side, but offers easy integration on C# side.
> 
> So, these are 3 options. If you tell me you goals, how you want to use rbfx, I can help you pick the best way for you.

wow,that's very kind of you.
I wonder if there is a way that can make things simple.For instance,copy folders and dlls to a C# project,then add reference to dlls and we can get a rbfx C# project.Just like I did.
Maybe my thought is ridiculous but...I am a student and feel headache with c++/cmake things.That is too professional for noobs like me.And that's why I choose rbfx not urho3d.
No offence,will you add functions like godot?I have learnt something about 2D games.In godot,we can do anything easily.Including writing codes and using editor.
Maybe I should listen to @rokups and use nuget?(I can not install the vsix file which is made by@gleblebedev )
Or...maybe I should use engines like unity/UE?I wonder if It is too early for me to get in touch with open source project.

**Comment by rokups** [comment]
> Or...maybe I should use engines like unity/UE?Maybe it is too early for me to get in touch with open source projects.

If you want to make games - definitely use Unity/Godot. rbfx is quite rough at the edges and we are making it with a code-first mindset. This means that you would inevitably have to fix bug or add new features in order to complete a game. Other engines are simply better if you just want to make games.

**Comment by eugeneko** [comment]
> I wonder if there is a way that can make things simple.For instance,copy folders and dlls to a C# project,then add reference to dlls and we can get a rbfx C# project.Just like I did.

"Simple" way is to use C# nuget. CMake and C++ require certain skill level to handle.

> No offence,will you add functions like godot?I have learnt something about 2D games.In godot,we can do anything easily.Including writing codes and using editor.

Gogot has full-time developers, Urho and rbfx do not. So, rbfx will not have the same amount of manpower invested, and therefore it will have less stuff in general. We add new things from time to time, but it will never be as much as for commerical game engine.

If your goal is to make games with the least effort and time spent, you should probably just pick Unity/UE/Godot, and ignore all uncommon engines.

**Comment by SoNewBee** [comment]
OK,I am gonna switch to unity/UE.(English is not my first language,pardon my grammar or words mistake in these days)
BTW,all of you did a good job,please keep your good work.
And...All of you are enthusiastic.Thanks for your patient.I will close this issue and I am gonna keep learning.
Good bye~
