### ISSUE TITLE
Shadow map on terrain bug

### ISSUE THREAD

**Issue by gleblebedev** [rbfx/rbfx#414]
Deferred PBR:

![image](https://user-images.githubusercontent.com/2943937/174897627-bcaa1ea9-72d1-4168-af00-215f6042ef50.png)

Forward render:

![image](https://user-images.githubusercontent.com/2943937/174897697-ff0f5365-4298-47a6-8d8f-f39a81aadde5.png)

**Comment by eugeneko** [comment]
@gleblebedev Is it relevant?

**Comment by gleblebedev** [comment]
> @gleblebedev Is it relevant?

I didn't touch terrain for a long time. We should ask Tuxifan.

**Comment by eugeneko** [comment]
Reopen if the bug persists.
