### ISSUE TITLE
MaterialInspectorWidget.cpp:551:24: error: format string is not a string literal (potentially insecure) 

### ISSUE THREAD

**Issue by gleblebedev** [rbfx/rbfx#435]
FAILED

/__w/1/s/rbfx/Source/Urho3D/SystemUI/MaterialInspectorWidget.cpp
/__w/1/s/rbfx/Source/Urho3D/SystemUI/MaterialInspectorWidget.cpp:551:24: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
        ui::SetTooltip(desc.hint_.c_str());
                       ^~~~~~~~~~~~~~~~~~

/__w/1/s/rbfx/Source/Urho3D/SystemUI/SceneHierarchyWidget.cpp:304:24: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
        ui::SetTooltip(hint);
                       ^~~~

**Comment by rokups** [comment]
Fixed by #436.
