### ISSUE TITLE
Sound in web builds is broken

### ISSUE THREAD

**Issue by rokups** [rbfx/rbfx#477]
7057c81 was supposed to fix sound, by initializing application from a user callback. Warning about audio initialization is gone, but sound still does not work. This is what i figured out so far:

- Sound device does get opened the first time
- At some point `Audio::deviceID_` gets reset, even if comment out code that does this

This needs to be debugged, but i cant figure out how to set up source level debugging in web builds, help needed. One thing to note - debug web builds fail to run with an odd exception. RelWithDebInfo builds work, but they fail with same assert if `-O2` is removed from build parameters.

Debug build exception:
```
Uncaught RuntimeError: Aborted(Assertion failed)
    abort http://0.0.0.0:8000/Samples.js:941
    assert http://0.0.0.0:8000/Samples.js:472
    removeRunDependency http://0.0.0.0:8000/Samples.js:893
    onload http://0.0.0.0:8000/Samples.js:24
    EventHandlerNonNull* http://0.0.0.0:8000/Samples.js:24
```
Failing asserts checks whether "Resources.js.loader" is a previously registered dependency.

@eugeneko please debug audio part, since you have been able to do source level debugging in the past.

**Comment by eugeneko** [comment]
@rokups debug builds now start

**Comment by eugeneko** [comment]
@rokups Does sound work in web samples now? It works for me.

**Comment by rokups** [comment]
Yeah looks like it works now.
