### ISSUE TITLE
urho3d is dead

### ISSUE THREAD

**Issue by tigerpeng** [rbfx/rbfx#524]
urho3d is dead, can rbfx be merged into the final version (english 1.9.0)?
 rbfx is lightweight and efficient code ,especially for xr project.
 I'd be happy to share my earnings to this project when I use this engine.

**Comment by rokups** [comment]
Urho3D is dead :(

We can not merge anything to urho repo because we have no access and only person with access is not going to allow it. Besides, it would be a bad idea because rbfx is not Urho3D and this would result in replacing a project with a different one.

rbfx lives here and you can use this repo. We did keep up with sane updates from upstream Urho3D as long as they made sense. Truth is it went off the rails before 1.9.0, so naturally we did not merge that stuff. But there wasnt anything that useful anyway.

**Comment by 1vanK** [comment]
Urho3D engine archiving was agreed with its creator, who is now engaged in another engine https://github.com/cadaver/turso3d

> rbfx is lightweight and efficient code ,especially for xr project.

rbfx was created by a toxic person who proposed all kinds of rubbish changes to Urho3D and could not agree with other developers

In any case, rbfx is also close to death

**Comment by tijon1** [comment]
> rbfx was created by a toxic person who proposed all kinds of rubbish changes to Urho3D and could not agree with other developers
> 
> In any case, rbfx is also close to death

🤣

**Comment by 1vanK** [comment]
> you sure do like randomly popping up and talking shit about rbfx.

Oh, I see a gathering of Baltic ragamuffins has formed here. rokups do like randomly popping up and send Hitler photo of Hitler in private messages.

**Comment by tijon1** [comment]
> 

I'm Russian-Estonian 🤣 so not quite fully Baltic

**Comment by 1vanK** [comment]
> I'm Russian-Estonian 🤣 so not quite fully Baltic

Русские везде есть, русский это не национальность, а менталитет. В России 190+ народов и они более русские, чем ты

**Comment by rokups** [comment]
@iSLC i got you covered fam, 1vanK is immortalized here: https://urho4d.github.io/ 😁

**Comment by 1vanK** [comment]
> For you to see this issue, you must have the rbfx repository on `Watch` mode or regularly check the repo. You weren't even remotely mentioned to get a notification about this issue. So don't play the "_i don't even care about it_" card anymore.
> 
> This is actually a great opportunity for other people to get an idea of what's been happening around here. Since, you know, the forum is gone and all traces of your toxic behavior along with it.
> 
> @tigerpeng when @rokups said "_only person with access is not going to allow it_". This is what he meant. And hopefully all is clear now.

You yourself came up with a theory about some kind of card, conducted an "investigation" and found a refutation. You are claiming the Pulitzer Prize

**Comment by iSLC** [comment]
You are beyond delusional. But keep going. Everyone is watching.

**Comment by 1vanK** [comment]
> You are beyond delusional. But keep going. Everyone is watching.

Don't be upset, go complain about me to your husband or whatever it is with you

**Comment by 1vanK** [comment]
> Can you elaborate on that?

I recommended that you go and satisfy your husband, as is customary in Europe

**Comment by iSLC** [comment]
Do you believe it shouldn't be? Do you have an issue with such behavior?

**Comment by 1vanK** [comment]
Are you a passive homosexual or an active one?

**Comment by iSLC** [comment]
> Are you a passive homosexual or an active one?

What does it matter to you? Does either offended so much to randomly bring it into conversation?

**Comment by 1vanK** [comment]
> What does it matter to you? Does either offend so much to randomly bring it into conversation?

Why are you shy?

**Comment by tijon1** [comment]
> @iSLC What slackers like you are capable of is easy to see here: https://github.com/u3d-community/U3D

just admit that Turso won't go anywhere and that RBFX is way better than your project. Name all the flaws with RBFX if it is so bad.

**Comment by tijon1** [comment]
> > just admit that Turso won't go anywhere and that RBFX is way better than your project. Name all the flaws with RBFX if it is so bad.
> 
> Если ты русский, как ты утверждаешь, то приходи на русский форум https://gamedev.ru/community/urho3d/forum/?id=211266&page=359&m=5705457#m5381 Там это вопрос много раз обсуждался

Name the flaws here please.

**Comment by iSLC** [comment]
> > What does it matter to you? Does either offend so much to randomly bring it into conversation?
> 
> Why are you shy?

I'm just genuinely curious why are you so offended by something outside the topic. And why this sudden interest in someone's sexual orientation.

Do you have a problem with LGBT community? Or maybe you are a part of that community and I may have offended you in some way. In which case let me know where and how so I can apologise properly.

**Comment by 1vanK** [comment]
> I'm just genuinely curious why are you so offended by something outside the topic. And why this sudden interest in someone's sexual orientation.
> 
> Do you have a problem with LGBT community? Or maybe you are a part of it and I may have offended you in some way. In which case let me know where and how so I can apologise properly.

I'm just trying to figure out if I have a problem with LGBT. And you're trying to avoid the answer.

**Comment by 1vanK** [comment]
> LGBT community

Do you mean rbfx users?

**Comment by iSLC** [comment]
> > I'm just genuinely curious why are you so offended by something outside the topic. And why this sudden interest in someone's sexual orientation.
> > Do you have a problem with LGBT community? Or maybe you are a part of it and I may have offended you in some way. In which case let me know where and how so I can apologise properly.
> 
> I'm just trying to figure out if I have a problem with LGBT. And you're trying to avoid the answer.

So any details about my sexual orientation would help you establish if you have a problem with LGBT community?

I'm quite confused. For the sake of argument. Let's say I am. What would your problem be now?

Would you hate LGBT community or not? Just because of me?

**Comment by 1vanK** [comment]
I despise the LGBT community and have no problem with it. At the moment I'm trying to find out if I have problems with the LGBT community in the face of you.

**Comment by tijon1** [comment]
@1vanK Could you please tell me what's wrong with rbfx though?

**Comment by 1vanK** [comment]
> Could you please tell me what's wrong with rbfx though?

Конечно, приходи на наш форум

**Comment by tijon1** [comment]
> 

I asked to reply here, not your forum.

**Comment by 1vanK** [comment]
Ты же русский или ни слова не понимаешь по русски? ))

**Comment by tijon1** [comment]
> > I asked to reply here, not your forum.
> 
> Это не мой форум, это русский форум

I don't care what forum it is, but I want you to reply the issues with rbfx here to not make the discussion go off into the russian forum.

**Comment by tijon1** [comment]
> Тогда тебе не повезло

Well, this thread is stupid nonsense then.

**Comment by iSLC** [comment]
> I despise the LGBT community and have no problem with it. At the moment I'm trying to find out if I have problems with the LGBT community in the face of you.

You just said you despise the LGBT community. How can I affect that?

Do you have a thing for me or something? Something that would help you change your mind?

Genuinely confused. This is going nowhere.

**Comment by 1vanK** [comment]
> You just said you despise the LGBT community. How can I affect that?
> 
> Do you have a thing for me or something? Something that would help you change your mind?
> 
> Genuinely confused. This is going nowhere.

I'll just have a reason to respect you even less

**Comment by iSLC** [comment]
> I'll just have a reason to respect you even less

You're not very sane. That's all I'm saying. Hat all you want. But at the end of the day. Someone being a part of a community should not be an issue on something that has nothing to do with it.

**Comment by iSLC** [comment]
> Well, do you consider homosexuality to be the norm when pedophilia, bestiality and other psychological illnesses become the norm for you?

Where are you even getting this from? You're just spouting nonsense in a topic that has nothing to do with it.

**Comment by 1vanK** [comment]
I think you're afraid to say what you really think. This is your European freedom of speech.

**Comment by iSLC** [comment]
> Do you have a problem talking about LGBT community?

Yes I have a problem when only hate is involved. You just said that you despise it and have no problem doing so. That you would hate anyone being a part of it. Actually, having less respect for that person (*in your words*). As if he would be less than human to deserve equal respect.

So why should I engage in that topic of discussion? Do you think that's what "*freedom of speech*" means? Being able to hate on communities with no remorse and/or repercussions?

You are clearly mistaken and a bit out of line to demand anything else.

**Comment by 1vanK** [comment]
Hate is too strong an emotion. Before, I didn't care, but now I despise you, because the aggressive minority with psychological problems impose their will on the majority. You spoil series, games and so on with their influence.

**Comment by iSLC** [comment]
You are so wrong and so delusional at the same time that it's unbelievable. You just assume things that have never affected you or anyone you know of. You're simply regurgitating someone else's hateful agenda. Also `despise` is a synonym for `hate`. Maybe not as strong but still hate, nonetheless.

**Comment by 1vanK** [comment]
> Also `despise` is a synonym for `hate`.

I don't know the subtleties of the English language. In Russian, "презрение" and "ненависть" have a huge difference.

**Comment by 1vanK** [comment]
By the way, how do you feel about the bullying of JK Rowling?

**Comment by iSLC** [comment]
I'm done going even more off-topic. This has nothing to do with anything discussed so far.

**Comment by 1vanK** [comment]
> I'm done going even more off-topic. This has nothing to do with anything discussed so far.

This is the difference between us. Remember, weak European, if you try to cancel the Russian, the Russian will avenge you all.

**Comment by 1vanK** [comment]
Or is it "different"?

**Comment by iSLC** [comment]
> Or is it "different"?

Yes it is damn "different". We're in a GH issue about merging a fork into upstream. Why should discussions about extreme political views and disdain towards someone's sexual orientation be a part of it? Are you hearing yourself?

**Comment by 1vanK** [comment]
> Yes it is damn "different". We're in a GH issue about merging a fork into upstream. Why should discussions about extreme political views and disdain towards someone's sexual orientation be a part of it? Are you hearing yourself?

Then why did you start talking from offtopic?

**Comment by iSLC** [comment]
> Then why did you start talking from offtopic?

> By the way, how do you feel about the bullying of JK Rowling?

Yes, I am the one doing. My bad pimp.

**Comment by 1vanK** [comment]
> Yes, I am the one doing it. My bad, pimp.

Do you plan to cut off your penis and enlarge your breasts? Rowling said you won't get your period, prove it to her.

**Comment by iSLC** [comment]
It doesn't affect you. None of this will ever affect you. Mind your own business (*and body*). Just stop with trying so much. Someone might thing you like it or something. Since you said it's not `hate` that you feel. It must be the opposite.

**Comment by 1vanK** [comment]
> It doesn't affect you. None of this will ever affect you. Mind your own business (_and body_). Just stop with trying so much. Someone might thing you like it or something. Since you said it's not `hate` that you feel. It must be the opposite.

You're wrong. This will affect me. Let me know if you're going to cut off your penis. This will lift my spirits. I hope you don't mind cutting off your penis?

**Comment by iSLC** [comment]
> You're wrong. This will affect me. Let me know if you're going to cut off your penis. This will lift my spirits. I hope you don't have problems with cut off your penis?

Why are you so happy about men without penis? That and the sudden interest in my sexual orientation. Where are you going with this? Is this a confession or something?

**Comment by 1vanK** [comment]
> Why are you so happy about men without penis? That and the sudden interest in my sexual orientation. Where are you going with this? Is this a confession or something?

I'm just wondering why you always try to evade the answer. Do you have any problems with this?

**Comment by tijon1** [comment]
> > Well, this thread is stupid nonsense then.
> 
> By the way, I heard that the Baltic brothers are resisting the LGBT infection, how do you feel about this?

LGBT hasn't reached me yet but if it does reach me in a way that is noticeable, then that's a bad thing.
I personally don't care if someone is quiet and treat it like something personal they don't tell everyone about but if they are loud and extreme, then they better go away from here.

**Comment by 1vanK** [comment]
> LGBT hasn't reached me yet but if it does reach me in a way that is noticeable, then that's a bad thing.
> I personally don't care if someone is quiet and treat their oreintation and sexuality like something personal they don't tell everyone about but if they are loud and extreme, then they better go away from here.

This is my Russian friend xD

**Comment by iSLC** [comment]
> > Why are you so happy about men without penis? That and the sudden interest in my sexual orientation. Where are you going with this? Is this a confession or something?
> 
> I'm just wondering why you always try to evade the answer. Do you have any problems with this?

I'm not evading any answer. I just don't understand why are you so excited about it. And why are you so adamant about me doing it. Since you're the one that brought it up in the first place :-/

**Comment by tijon1** [comment]
IMO This thread has devolved into nonsense and the LGBT talk isn't worth talking about here, just go to DMs.
But then again, this is entertainment.

**Comment by 1vanK** [comment]
> I'm not evading any answer. I just don't understand why are you so excited about it. And why are you so adamant about me doing it. Since you're the one that brought it up in the first place :-/

There wasn't a single answer. You asked about my attitude towards LGBT community. I answered you. But I didn't get any response from you.

**Comment by iSLC** [comment]
> IMO This thread has devolved into nonsense and the LGBT talk isn't worth talking about here, just go to DMs. But then again, this is entertainment and the people watching with popcorn wouldn't like to see this thread end .

This is what he always does. He brings weird stuff into discussions that are completely off topic. I think he has some secret fetish about men without penis. There's no other way to explain his excitement on the topic since no one else brought it up.

**Comment by 1vanK** [comment]
> This is what he always does. He brings weird stuff into discussions that are completely off topic. I think he has some secret fetish about men without penis. There's no other way to explain his excitement on the topic since no one else brought it up.

In this topic, the Balts, the Chinese and the Russians. You're trying in vain to win someone over to your side. It seems to me that everyone will be interested in your modification, because this is normal. Or abnormal?

**Comment by iSLC** [comment]
Nobody is interested in what I'm doing but you. You're the only one that keeps being interested and brings it up into discussion.

I wonder where you'll derail next. What positions I like.

**Comment by 1vanK** [comment]
> Nobody is interested in what I'm doing but you. You're the only one that keeps being interested and brings it up into discussion.
> 
> I wonder where you'll derail next. What positions I like.

The more you try to avoid the answer, the stronger my interest.

**Comment by 1vanK** [comment]
Okay, I get that you're shy. If you're going to cut off your penis, then just keep evading the answer.

**Comment by iSLC** [comment]
> ..., the stronger my interest.

Why does that not surprise me.

There's no "*trying to win you over*". You're already there. You're just in denial. Keep trying to make it seem otherwise. You've only making it more obvious.

**Comment by 1vanK** [comment]
> Why does that not surprise me.
> 
> There's no "_trying to win you over_". You're already there. You're just in denial. Keep trying to make it seem otherwise. You're only making it more obvious.

I understood you ;) By the way, do you have Instagramm? I don't want to miss it
