### ISSUE TITLE
Shader compilation error on OpenGL ES3

### ISSUE THREAD

**Issue by gleblebedev** [rbfx/rbfx#528]
E/Urho3D: [00:33:16] [error] [main] : Failed to compile vertex shader PBRLitSolid( NORMALMAP URHO3D_ADDITIVE_LIGHT_PASS URHO3D_GEOMETRY_STATIC URHO3D_HAS_SHADOW URHO3D_LIGHT_POINT URHO3D_SHADOW_PCF_SIZE=3 URHO3D_SPECULAR=1 URHO3D_VERTEX_HAS_NORMAL URHO3D_VERTEX_HAS_TEXCOORD0 URHO3D_VERTEX_HAS_TEXCOORD1):
    Shader Files:
    1: Shaders/GLSL/v2/P_FXAA2.glsl
    2: Shaders/GLSL/v2/_Config.glsl
    3: Shaders/GLSL/v2/_Config_Basic.glsl
    4: Shaders/GLSL/v2/_Config_Material.glsl
    5: Shaders/GLSL/v2/_Uniforms.glsl
    6: Shaders/GLSL/v2/_VertexLayout.glsl
    7: Shaders/GLSL/v2/_VertexTransform.glsl
    8: Shaders/GLSL/v2/_VertexScreenPos.glsl
    9: Shaders/GLSL/v2/_Samplers.glsl
    10: Shaders/GLSL/v2/PBRLitSolid.glsl
    11: Shaders/GLSL/v2/LitSolid.glsl
    12: Shaders/GLSL/v2/M_Default.glsl
    13: Shaders/GLSL/v2/_Material.glsl
    14: Shaders/GLSL/v2/_GammaCorrection.glsl
    15: Shaders/GLSL/v2/_BRDF.glsl
    16: Shaders/GLSL/v2/_IndirectLighting.glsl
    17: Shaders/GLSL/v2/_DirectLighting.glsl
    18: Shaders/GLSL/v2/_Shadow.glsl
    19: Shaders/GLSL/v2/_Fog.glsl
    20: Shaders/GLSL/v2/_Material_DepthOnly.glsl
    21: Shaders/GLSL/v2/_Material_Common.glsl
    22: Shaders/GLSL/v2/_Material_Vertex.glsl
    23: Shaders/GLSL/v2/_Material_Pixel_SurfaceData.glsl
    24: Shaders/GLSL/v2/_Material_Pixel_Fill.glsl
    25: Shaders/GLSL/v2/_Material_Pixel_Evaluate.glsl
    26: Shaders/GLSL/v2/PBRTerrainBlend.glsl
    27: Shaders/GLSL/v2/M_LegacyTerrain.glsl
    
    WARNING: 3:91: extension 'GL_ARB_shading_language_420pack' is not supported
    WARNING: 3:92: extension 'GL_EXT_shader_texture_lod' is not supported
    ERROR: 7:152: 'iTangent' : undeclared identifier 
    ERROR: 7:152: 'xyz' :  field selection requires structure, vector, or matrix on left hand side 
    ERROR: 7:152: 'normalize' : no matching overloaded function found 
    ERROR: 7:152: 'assign' :  cannot convert from 'const float' to '3-component vector of float'
    ERROR: 7:153: 'w' :  field selection requires structure, vector, or matrix on left hand side 
    ERROR: 5 compilation errors.  No code generated.

**Comment by gleblebedev** [comment]
it isn't just M_LegacyTerrain.glsl:

E/Urho3D: [00:33:16] [error] [main] : Failed to compile vertex shader PBRLitSolid( NORMALMAP URHO3D_AMBIENT_DIRECTIONAL URHO3D_AMBIENT_PASS URHO3D_GEOMETRY_STATIC URHO3D_NUM_VERTEX_LIGHTS=4 URHO3D_SPECULAR=1 URHO3D_VERTEX_HAS_NORMAL URHO3D_VERTEX_HAS_TEXCOORD0 URHO3D_VERTEX_HAS_TEXCOORD1):
    Shader Files:
    1: Shaders/GLSL/v2/P_FXAA2.glsl
    2: Shaders/GLSL/v2/_Config.glsl
    3: Shaders/GLSL/v2/_Config_Basic.glsl
    4: Shaders/GLSL/v2/_Config_Material.glsl
    5: Shaders/GLSL/v2/_Uniforms.glsl
    6: Shaders/GLSL/v2/_VertexLayout.glsl
    7: Shaders/GLSL/v2/_VertexTransform.glsl
    8: Shaders/GLSL/v2/_VertexScreenPos.glsl
    9: Shaders/GLSL/v2/_Samplers.glsl
    10: Shaders/GLSL/v2/PBRLitSolid.glsl
    11: Shaders/GLSL/v2/LitSolid.glsl
    12: Shaders/GLSL/v2/M_Default.glsl
    13: Shaders/GLSL/v2/_Material.glsl
    14: Shaders/GLSL/v2/_GammaCorrection.glsl
    15: Shaders/GLSL/v2/_BRDF.glsl
    16: Shaders/GLSL/v2/_IndirectLighting.glsl
    17: Shaders/GLSL/v2/_DirectLighting.glsl
    18: Shaders/GLSL/v2/_Shadow.glsl
    19: Shaders/GLSL/v2/_Fog.glsl
    20: Shaders/GLSL/v2/_Material_DepthOnly.glsl
    21: Shaders/GLSL/v2/_Material_Common.glsl
    22: Shaders/GLSL/v2/_Material_Vertex.glsl
    23: Shaders/GLSL/v2/_Material_Pixel_SurfaceData.glsl
    24: Shaders/GLSL/v2/_Material_Pixel_Fill.glsl
    25: Shaders/GLSL/v2/_Material_Pixel_Evaluate.glsl
    
    WARNING: 3:91: extension 'GL_ARB_shading_language_420pack' is not supported
    WARNING: 3:92: extension 'GL_EXT_shader_texture_lod' is not supported
    ERROR: 7:152: 'iTangent' : undeclared identifier 
    ERROR: 7:152: 'xyz' :  field selection requires structure, vector, or matrix on left hand side 
    ERROR: 7:152: 'normalize' : no matching overloaded function found 
    ERROR: 7:152: 'assign' :  cannot convert from 'const float' to '3-component vector of float'
    ERROR: 7:153: 'w' :  field selection requires structure, vector, or matrix on left hand side 
    ERROR: 5 compilation errors.  No code generated.

**Comment by eugeneko** [comment]
Reopen if relevant after Diligent refactoring
