### ISSUE TITLE
Slow Navmesh Build

### ISSUE THREAD

**Issue by KatekovAnton** [rbfx/rbfx#532]
Hi. I increased a size of the navmesh and noticed that building a navmes now takes 20 seconds. 

Maybe this part be done in a parallel loop?
https://github.com/rbfx/rbfx/blob/master/Source/Urho3D/Navigation/NavigationMesh.cpp#L1502-L1515

Thank you

**Comment by eugeneko** [comment]
Navmesh build can be spread across multiple frames.
Also, navmeshes can be now safely built partially.
Parallel algos would be nice, but are not a priority.
