### ISSUE TITLE
Rendering trees & leaves

### ISSUE THREAD

**Issue by Erlangist** [rbfx/rbfx#550]
It seems that there is no way to render tree leaves in the usual way, using textures with alpha channel and writing depth when and only when pixels from texture are opaque.

**Comment by JTippetts** [comment]
You should be able to use any standard technique with a diffuse texture and define ALPHAMASK in your material definition in order to have it discard pixels with < 0.5 alpha. In the material .xml file, the line `<shader psdefines="ALPHAMASK" />` should enable it.
