### ISSUE TITLE
BorderImage::SetMaterial() is broken

### ISSUE THREAD

**Issue by Erlangist** [rbfx/rbfx#558]
After changes in commit #bc827bfeba25fcbad53e3b1d22a60ecfb3210e86 there is no clear way to render something in UI with custom material.

Changing from drawQueue->Reset(false); to drawQueue->Reset(); is the problem.

**Comment by eugeneko** [comment]
Please try this commit:
https://github.com/rbfx/rbfx/tree/ek/ui-material

**Comment by Erlangist** [comment]
It mostly works, yet there is an issue with uniforms. I'm getting `[error] [main] : Shader parameter #447847554 'Fill' shall be stored in group 4 instead of group 5` when passing a single float to the shader

**Comment by eugeneko** [comment]
Are you using your custom shaders? Can you share it if that's the case?

**Comment by Erlangist** [comment]
```
#define URHO3D_VERTEX_HAS_COLOR
#define URHO3D_GEOMETRY_STATIC
#include "_Material.glsl"

#ifdef VERTEXCOLOR
    varying vec4 vColor;
#endif

UNIFORM_BUFFER_BEGIN(4, XObject)
    UNIFORM_HIGHP(float cFill)
UNIFORM_BUFFER_END(4, XObject)

#ifdef URHO3D_VERTEX_SHADER

void main()
{
    VertexTransform vertexTransform = GetVertexTransform();
    gl_Position = WorldToClipSpace(vertexTransform.position.xyz);
    ApplyClipPlane(gl_Position);

    #ifdef URHO3D_VERTEX_HAS_COLOR
        vColor = iColor;
    #endif
}

#endif
#ifdef URHO3D_PIXEL_SHADER

void main()
{
    vec4 rcolor = vec4(vColor.rgb, cFill);
        
    gl_FragColor = rcolor;
}

#endif
```

**Comment by eugeneko** [comment]
Define URHO3D_CUSTOM_MATERIAL_UNIFORMS in the beginning so the index 4 is
not taken by default uniforms. And if you get errors, try avoid including
Material.glsl since it is for standard-ish shaders.

**Comment by Erlangist** [comment]
After some trickstery it worked. The shader is listed below.
I think that an example of custom material in UI is necessary.

```
#define URHO3D_CUSTOM_MATERIAL_UNIFORMS
#include "_Config.glsl"
#include "_Uniforms.glsl"

VERTEX_OUTPUT(vec4 vColor)

#ifdef URHO3D_VERTEX_SHADER
VERTEX_INPUT(vec3 iPos)
VERTEX_INPUT(vec4 iColor)
#endif

UNIFORM_BUFFER_BEGIN(4, Material)
    UNIFORM(float cFill)
UNIFORM_BUFFER_END(4, Material)

#ifdef URHO3D_VERTEX_SHADER

void main()
{
    gl_Position = vec4(iPos, 1.0) *cViewProj;
    vColor = iColor;
}

#endif
#ifdef URHO3D_PIXEL_SHADER

void main()
{
    vec4 rcolor = vec4(vColor.rgb, cFill);
        
    gl_FragColor = rcolor;
}

#endif
```
