### ISSUE TITLE
Error creating new project

### ISSUE THREAD

**Issue by VinnyVicious** [rbfx/rbfx#611]
This error appears when trying to create or open a new project from the Editor:

```
sh: line 1: zenity: command not found
```

**Comment by gleblebedev** [comment]
You need zenity for a folder selection dialog

**Comment by eugeneko** [comment]
I wonder if we can drop native file dialogs, they are used in 2 places only (Editor launch page, open project).

**Comment by VinnyVicious** [comment]
For anyone seeing this in the future:

https://packages.ubuntu.com/lunar/zenity
https://packages.fedoraproject.org/pkgs/zenity/zenity/
