### ISSUE TITLE
LitWaterPBR is not depth-aware

### ISSUE THREAD

**Issue by WyrdanGames** [rbfx/rbfx#623]
I have already spoken to gleblebedev about this problem. He took a quick look at it and said depth awareness is missing.

The problem is that the shader is doing the noise always both ways and not only under the water.

You can see it in the screenshot:

![LitWaterPBR](https://github.com/rbfx/rbfx/assets/11030095/00bc5e04-dcd6-4387-8c69-14fde15feb87)

**Comment by gleblebedev** [comment]
![image](https://github.com/rbfx/rbfx/assets/2943937/2b21b8cf-9dc1-4f71-8c9f-cc22704da061)

**Comment by gleblebedev** [comment]
Fixed in https://github.com/rbfx/rbfx/pull/625

**Comment by WyrdanGames** [comment]
works for me ty!

![grafik](https://github.com/rbfx/rbfx/assets/11030095/c8046ebc-22ee-440f-b062-6151c96f91d0)
