### ISSUE TITLE
Editor inspector - issue when selecting things from the 'Resources' tab

### ISSUE THREAD

**Issue by LxrdKxnny** [rbfx/rbfx#645]
There seems to be an issue when selecting something such as a '.scene' file, '.xml' files, etc from the 'Resources' tab. The editor inspector shows the properties for the selected file from the 'Resources' tab but only for a split second until it disappears again, making it impossible to be able to properties for the selected file. I've attached a quick video so you can see what I mean.

https://github.com/rbfx/rbfx/assets/94867124/cee006ca-c4f3-43fd-991f-ba98859fcff0

I'm using "rebelfork-sdk-Windows-msvc-dbg-dll-x64-latest" from Releases.

**Comment by eugeneko** [comment]
Does inspector work if you click on scene nodes?
I cannot repro this issue for whatever reason.

**Comment by LxrdKxnny** [comment]
> Does inspector work if you click on scene nodes? I cannot repro this issue for whatever reason.

The inspector works fine if I click on scene nodes, it's only when clicking on resources that the inspector won't show the properties for the selected resource.

**Comment by LxrdKxnny** [comment]
This issue has now been fixed since the last release. Closing.

**Comment by LxrdKxnny** [comment]
I'm sorry, I've re-opened this because it hasn't actually been fixed. I now know how you can re-produce the issue. In the Hierarchy, disable "Show Components" and then click on a resource from the "Resources" tab and you'll see the problem happening. I didn't realise it only happened when disabling "Show Components" in the hierarchy.

**Comment by eugeneko** [comment]
Thanks, I can reproduce this issue now.

**Comment by LxrdKxnny** [comment]
> Thanks, I can reproduce this issue now.

You're welcome! :)
