### ISSUE TITLE
using plugin issue

### ISSUE THREAD

**Issue by crystaldev3d** [rbfx/rbfx#648]
Hello, developers! Happy New Year! I wish you a productive next year for the engine and the community.

I had some time to play with the engine.  And I have the following problem. 
I can not create a component from my own plugin. In the specified code section of the example it always returns null.
https://github.com/crystaldev3d/rbfx/blob/reflection-plugin-test/Source/MyGame/Source/Main.cpp#L132
And I don't understand what the problem is.
![pic1](https://github.com/rbfx/rbfx/assets/95735962/d761e0ba-6509-4130-bf63-98d33126725c)

The project consists of a plugin (collection of components that need to be exposed to the editor and used by game.exe) 
(https://github.com/crystaldev3d/rbfx/tree/reflection-plugin-test/Source/MyGamePlugin)

and a program that uses this plugin. 
(https://github.com/crystaldev3d/rbfx/tree/reflection-plugin-test/Source/MyGame)

**Comment by eugeneko** [comment]
Do you register your type anywhere?

**Comment by crystaldev3d** [comment]
Of course, here RegisteObject()
https://github.com/crystaldev3d/rbfx/blob/reflection-plugin-test/Source/MyGamePlugin/FPSCameraController.cpp#L41
and here 
https://github.com/crystaldev3d/rbfx/blob/reflection-plugin-test/Source/MyGamePlugin/GamePlugin.cpp#L61

**Comment by eugeneko** [comment]
@crystaldev3d In this case, plugin is probably not loaded. No errors in logs? Engine should report an error if it tried to load plugin which it doesn't know about. If you use static build, you should statically link your plugin to the executable.

**Comment by crystaldev3d** [comment]
In the end I think I should pay attention to rbfx/sample-project, there everything is set up and works out of the box. Besides my variant (game.exe(logic) + dll(components)) will not work in the editor, but sample-project will work. because the project dll is loaded by both the editor and the launcher. 
Sorry for the time. I guess this can be closed.
