### ISSUE TITLE
Asset Test.blend was not processed: Cannot load output pipe

### ISSUE THREAD

**Issue by CG-SS** [rbfx/rbfx#667]
Hey team, I'm trying to import a very simple model using the Editor, which is basically just a Blender cube, however, it fails with the following error:

```
Asset Test.blend was not processed: Cannot load output pipe
```

I currently have Blender added under the Settings path, and my Blender .exe is the following version:

![image](https://github.com/rbfx/rbfx/assets/28794929/f1d22bf0-a8f5-4988-b8d0-3eaddae4973b)

This is happening under the latest `master`.

**Comment by eugeneko** [comment]
@CG-SS Can you try to pass `--single-process` flag to the editor?

**Comment by CG-SS** [comment]
After some debugging, it seems that the error was caused because it couldn't find the rendering techniques. 

It looks like, on Windows, if you run the `Editor.exe` under `bin`, it can't really properly find the `CoreData` folder, due to how, at least if built with Microsoft Studio, you end up with a `Release/Debug` folder.

ALtho not really a 'solution', I moved the `Editor.exe`, `CoreData` and `EditorData` into the same folder. That way it works just fine, no need for `--singleprocess` either. Thanks all!
