### ISSUE TITLE
Is IK functional?

### ISSUE THREAD

**Issue by CG-SS** [rbfx/rbfx#677]
I see we have a `Urho3D/IK` but I don't see that Urho3D IK sample, wondering if IK is ready or is it being worked on?

**Comment by gleblebedev** [comment]
There is a sample scene that showcases all IK features.

**Comment by gleblebedev** [comment]
See  bin\Data\Scenes\InverseKinematics_0.xml for example. You can open bin folder in the editor as a project.

**Comment by CG-SS** [comment]
Any interest on having it as a Sample? I could look into it

**Comment by eugeneko** [comment]
@CG-SS I am not against the dedicated IK sample. I just didn't have the time and didn't feel the strong need to have it.
Sample scenes are easier to maintain.

If you decide to make IK sample, please try to keep it (relatively) simple.
