### ISSUE TITLE
RenderScope::ConsumeOpenGLError() is a performance bottleneck for web builds

### ISSUE THREAD

**Issue by plumgames** [rbfx/rbfx#726]
I don't know the context for why this was introduced but it's had a big impact on frame times on web, especially mobile web: https://github.com/rbfx/rbfx/commit/6ea256242038e5e136f0a13bb49e0e6993e1c100

I made a release web build of a small test scene with 10 static models in it with and without this change. The frame time cost of `ConsumeOpenGLError()` on desktop* web was **~5ms**, on mobile* web **~21ms**. 

Removing this fixes a lot of jitter issues on web buiilds since [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame) will compensate for frames that exceed the refresh rate frame budget by skipping calling the rbfx frame func to catch up.

In my fork I've added the option to turn off debug render scopes entirely via `URHO3D_DEBUG_GRAPHICS_SCOPES`, can PR this if this approach is ok.

https://github.com/plumgames/rbfx/blob/dev/Source/Urho3D/RenderAPI/RenderScope.h
https://github.com/plumgames/rbfx/blob/dev/Source/Urho3D/RenderAPI/RenderScope.cpp

*Hardware used: [desktop](https://www.amazon.com/ASUS-MiniPC-System-R5-4500U-Processor/dp/B08GL57TKL) [mobile](https://www.gsmarena.com/oneplus_11-11893.php)

**Comment by eugeneko** [comment]
I added this as workaround for weird error in my setup, maybe driver bug.

Do you observe any performance impact in native builds?

Render scope is useful for frame capturing, I don't think it's ever useful in Web builds.

**Comment by plumgames** [comment]
> Do you observe any performance impact in native builds?

No impact on the native macOS build, never tried opengl on the windows build.
