### ISSUE TITLE
Project Management landing window

### ISSUE THREAD

**Issue by PlasmaDev5** [rbfx/rbfx#77]
When opening the engine you are shown a blank window with no information on what to do. For many people this may look like the engine is broken, especially if they don't spot the file tab.

I feel it would be good to provide a window to create and manage existing projects. To help demonstrate what i have in mind and to maybe provide a starting point for further discussion i have created a quick mockup (im no artist)

![landingpageMockup](https://user-images.githubusercontent.com/3044415/57183577-51aaf000-6eaf-11e9-974e-4b2192154343.png)

**Comment by rokups** [comment]
Good to see you around!

True that first view needs some love. I skipped it mainly because i did not quite know how to fill the space so it didnt look mostly empty. That mockup looks great. We definitely must have this :)

**Comment by nem0** [comment]
Do what Godot does. :trollface:

**Comment by rokups** [comment]
Switch to vulkan? :trollface:

**Comment by rokups** [comment]
A simple landing screen + recent projects menu incoming.

![image](https://user-images.githubusercontent.com/19151258/59149304-78af9100-8a1c-11e9-9619-77380688c320.png)
